# Generated by Django 4.1.3 on 2022-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(max_length=50)),
                ('ProDesc', models.CharField(max_length=500)),
                ('ProPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProCreated', models.DateTimeField()),
            ],
        ),
    ]
