# Generated by Django 4.1.3 on 2022-12-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_prodesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProCost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProCreated',
            field=models.DateTimeField(verbose_name='Created In'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProDesc',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProName',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROIimage', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('PROIproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
