# Generated by Django 4.1.3 on 2022-12-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_procost_alter_product_procreated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATmain_category', models.CharField(max_length=50)),
                ('CATdes', models.TextField()),
                ('CATimg', models.ImageField(upload_to='category/')),
                ('CATparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
