# Generated by Django 4.1.3 on 2022-12-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_catparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNalternative', models.ManyToManyField(related_name='Alternative_Product', to='product.product')),
                ('PALNproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Product', to='product.product')),
            ],
        ),
    ]
