# Generated by Django 4.1.3 on 2022-12-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productalternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAcsessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCalternative', models.ManyToManyField(related_name='Acessoires', to='product.product')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Name', to='product.product')),
            ],
        ),
    ]
