# Generated by Django 4.1.3 on 2022-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_probrand_product_procategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Proimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='image'),
        ),
    ]
