# Generated by Django 4.1.3 on 2022-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_proimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Proslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
