# Generated by Django 4.1.3 on 2022-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prodiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProDiscountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discount Price'),
        ),
    ]
