# Generated by Django 4.1.3 on 2022-12-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_prodiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Proisbestsaller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Proisnew',
            field=models.BooleanField(default=True),
        ),
    ]
