# Generated by Django 4.1.3 on 2022-12-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRAname', models.CharField(max_length=50)),
                ('BRAdesc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARname', models.CharField(max_length=50)),
                ('VARdesc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
